language: node_js

sudo: false

node_js:
  - "10"

cache:
  apt: true
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --pure-lockfile

script:
  - npm run eslint
  - npm run build
