[build]
  command = "npm run build"
  publish = "/public"
  environment = { NODE_VERSION = "10", NODE_ENV = "production" }

[[redirects]]
  from = "/"
  to = "/zh-tw/"
  status = 302
  conditions = {Language = ["zh-tw", "zh-hk"]}

[[redirects]]
  from = "/"
  to = "/zh-cn/"
  status = 302
  conditions = {Language = ["zh", "zh-cn"]}

[[redirects]]
  from = "/"
  to = "/ru/"
  status = 302
  conditions = {Language = ["ru"]}

[[redirects]]
  from = "/"
  to = "/ko/"
  status = 302
  conditions = {Language = ["ko"]}

[[redirects]]
  from = "/"
  to = "/pt-br/"
  status = 302
  conditions = {Language = ["pt-br"]}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
